/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminTrashRouteImport } from './routes/admin/trash'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminAgenciesRouteImport } from './routes/admin/agencies'
import { Route as AdminAlbumsRouteRouteImport } from './routes/admin/albums/route'
import { Route as AdminAlbumsIndexRouteImport } from './routes/admin/albums/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetsSplatRouteImport } from './routes/api/assets/$'
import { Route as AdminAlbumsAlbumIdRouteImport } from './routes/admin/albums/$albumId'
import { Route as ApiAdminImagesUploadRouteImport } from './routes/api/admin/images/upload'
import { Route as ApiAdminModelsAvatarUploadRouteImport } from './routes/api/admin/models/avatar/upload'
import { Route as ApiAdminModelsAvatarDeleteRouteImport } from './routes/api/admin/models/avatar/delete'
import { Route as ApiAdminImagesUploadPrepareRouteImport } from './routes/api/admin/images/upload/prepare'
import { Route as ApiAdminImagesUploadCompleteRouteImport } from './routes/api/admin/images/upload/complete'
import { Route as ApiAdminImagesUploadCancelRouteImport } from './routes/api/admin/images/upload/cancel'
import { Route as ApiAdminModelsAvatarUploadPrepareRouteImport } from './routes/api/admin/models/avatar/upload/prepare'
import { Route as ApiAdminModelsAvatarUploadCompleteRouteImport } from './routes/api/admin/models/avatar/upload/complete'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrashRoute = AdminTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlbumsRouteRoute = AdminAlbumsRouteRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlbumsIndexRoute = AdminAlbumsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAlbumsRouteRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsSplatRoute = ApiAssetsSplatRouteImport.update({
  id: '/api/assets/$',
  path: '/api/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlbumsAlbumIdRoute = AdminAlbumsAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => AdminAlbumsRouteRoute,
} as any)
const ApiAdminImagesUploadRoute = ApiAdminImagesUploadRouteImport.update({
  id: '/api/admin/images/upload',
  path: '/api/admin/images/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminModelsAvatarUploadRoute =
  ApiAdminModelsAvatarUploadRouteImport.update({
    id: '/api/admin/models/avatar/upload',
    path: '/api/admin/models/avatar/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminModelsAvatarDeleteRoute =
  ApiAdminModelsAvatarDeleteRouteImport.update({
    id: '/api/admin/models/avatar/delete',
    path: '/api/admin/models/avatar/delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminImagesUploadPrepareRoute =
  ApiAdminImagesUploadPrepareRouteImport.update({
    id: '/prepare',
    path: '/prepare',
    getParentRoute: () => ApiAdminImagesUploadRoute,
  } as any)
const ApiAdminImagesUploadCompleteRoute =
  ApiAdminImagesUploadCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiAdminImagesUploadRoute,
  } as any)
const ApiAdminImagesUploadCancelRoute =
  ApiAdminImagesUploadCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => ApiAdminImagesUploadRoute,
  } as any)
const ApiAdminModelsAvatarUploadPrepareRoute =
  ApiAdminModelsAvatarUploadPrepareRouteImport.update({
    id: '/prepare',
    path: '/prepare',
    getParentRoute: () => ApiAdminModelsAvatarUploadRoute,
  } as any)
const ApiAdminModelsAvatarUploadCompleteRoute =
  ApiAdminModelsAvatarUploadCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiAdminModelsAvatarUploadRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin/albums': typeof AdminAlbumsRouteRouteWithChildren
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/albums/$albumId': typeof AdminAlbumsAlbumIdRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/albums/': typeof AdminAlbumsIndexRoute
  '/api/admin/images/upload': typeof ApiAdminImagesUploadRouteWithChildren
  '/api/admin/images/upload/cancel': typeof ApiAdminImagesUploadCancelRoute
  '/api/admin/images/upload/complete': typeof ApiAdminImagesUploadCompleteRoute
  '/api/admin/images/upload/prepare': typeof ApiAdminImagesUploadPrepareRoute
  '/api/admin/models/avatar/delete': typeof ApiAdminModelsAvatarDeleteRoute
  '/api/admin/models/avatar/upload': typeof ApiAdminModelsAvatarUploadRouteWithChildren
  '/api/admin/models/avatar/upload/complete': typeof ApiAdminModelsAvatarUploadCompleteRoute
  '/api/admin/models/avatar/upload/prepare': typeof ApiAdminModelsAvatarUploadPrepareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin': typeof AdminIndexRoute
  '/admin/albums/$albumId': typeof AdminAlbumsAlbumIdRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/albums': typeof AdminAlbumsIndexRoute
  '/api/admin/images/upload': typeof ApiAdminImagesUploadRouteWithChildren
  '/api/admin/images/upload/cancel': typeof ApiAdminImagesUploadCancelRoute
  '/api/admin/images/upload/complete': typeof ApiAdminImagesUploadCompleteRoute
  '/api/admin/images/upload/prepare': typeof ApiAdminImagesUploadPrepareRoute
  '/api/admin/models/avatar/delete': typeof ApiAdminModelsAvatarDeleteRoute
  '/api/admin/models/avatar/upload': typeof ApiAdminModelsAvatarUploadRouteWithChildren
  '/api/admin/models/avatar/upload/complete': typeof ApiAdminModelsAvatarUploadCompleteRoute
  '/api/admin/models/avatar/upload/prepare': typeof ApiAdminModelsAvatarUploadPrepareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin/albums': typeof AdminAlbumsRouteRouteWithChildren
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/albums/$albumId': typeof AdminAlbumsAlbumIdRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/admin/albums/': typeof AdminAlbumsIndexRoute
  '/api/admin/images/upload': typeof ApiAdminImagesUploadRouteWithChildren
  '/api/admin/images/upload/cancel': typeof ApiAdminImagesUploadCancelRoute
  '/api/admin/images/upload/complete': typeof ApiAdminImagesUploadCompleteRoute
  '/api/admin/images/upload/prepare': typeof ApiAdminImagesUploadPrepareRoute
  '/api/admin/models/avatar/delete': typeof ApiAdminModelsAvatarDeleteRoute
  '/api/admin/models/avatar/upload': typeof ApiAdminModelsAvatarUploadRouteWithChildren
  '/api/admin/models/avatar/upload/complete': typeof ApiAdminModelsAvatarUploadCompleteRoute
  '/api/admin/models/avatar/upload/prepare': typeof ApiAdminModelsAvatarUploadPrepareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/admin/albums'
    | '/admin/agencies'
    | '/admin/models'
    | '/admin/tags'
    | '/admin/trash'
    | '/api/$'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/orpc-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/admin/'
    | '/admin/albums/$albumId'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/albums/'
    | '/api/admin/images/upload'
    | '/api/admin/images/upload/cancel'
    | '/api/admin/images/upload/complete'
    | '/api/admin/images/upload/prepare'
    | '/api/admin/models/avatar/delete'
    | '/api/admin/models/avatar/upload'
    | '/api/admin/models/avatar/upload/complete'
    | '/api/admin/models/avatar/upload/prepare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/admin/agencies'
    | '/admin/models'
    | '/admin/tags'
    | '/admin/trash'
    | '/api/$'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/orpc-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/admin'
    | '/admin/albums/$albumId'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/albums'
    | '/api/admin/images/upload'
    | '/api/admin/images/upload/cancel'
    | '/api/admin/images/upload/complete'
    | '/api/admin/images/upload/prepare'
    | '/api/admin/models/avatar/delete'
    | '/api/admin/models/avatar/upload'
    | '/api/admin/models/avatar/upload/complete'
    | '/api/admin/models/avatar/upload/prepare'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/admin/albums'
    | '/admin/agencies'
    | '/admin/models'
    | '/admin/tags'
    | '/admin/trash'
    | '/api/$'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/orpc-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/admin/'
    | '/admin/albums/$albumId'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/admin/albums/'
    | '/api/admin/images/upload'
    | '/api/admin/images/upload/cancel'
    | '/api/admin/images/upload/complete'
    | '/api/admin/images/upload/prepare'
    | '/api/admin/models/avatar/delete'
    | '/api/admin/models/avatar/upload'
    | '/api/admin/models/avatar/upload/complete'
    | '/api/admin/models/avatar/upload/prepare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAssetsSplatRoute: typeof ApiAssetsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  ApiAdminImagesUploadRoute: typeof ApiAdminImagesUploadRouteWithChildren
  ApiAdminModelsAvatarDeleteRoute: typeof ApiAdminModelsAvatarDeleteRoute
  ApiAdminModelsAvatarUploadRoute: typeof ApiAdminModelsAvatarUploadRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trash': {
      id: '/admin/trash'
      path: '/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AdminTrashRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/albums': {
      id: '/admin/albums'
      path: '/albums'
      fullPath: '/admin/albums'
      preLoaderRoute: typeof AdminAlbumsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/albums/': {
      id: '/admin/albums/'
      path: '/'
      fullPath: '/admin/albums/'
      preLoaderRoute: typeof AdminAlbumsIndexRouteImport
      parentRoute: typeof AdminAlbumsRouteRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$': {
      id: '/api/assets/$'
      path: '/api/assets/$'
      fullPath: '/api/assets/$'
      preLoaderRoute: typeof ApiAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/albums/$albumId': {
      id: '/admin/albums/$albumId'
      path: '/$albumId'
      fullPath: '/admin/albums/$albumId'
      preLoaderRoute: typeof AdminAlbumsAlbumIdRouteImport
      parentRoute: typeof AdminAlbumsRouteRoute
    }
    '/api/admin/images/upload': {
      id: '/api/admin/images/upload'
      path: '/api/admin/images/upload'
      fullPath: '/api/admin/images/upload'
      preLoaderRoute: typeof ApiAdminImagesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/models/avatar/upload': {
      id: '/api/admin/models/avatar/upload'
      path: '/api/admin/models/avatar/upload'
      fullPath: '/api/admin/models/avatar/upload'
      preLoaderRoute: typeof ApiAdminModelsAvatarUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/models/avatar/delete': {
      id: '/api/admin/models/avatar/delete'
      path: '/api/admin/models/avatar/delete'
      fullPath: '/api/admin/models/avatar/delete'
      preLoaderRoute: typeof ApiAdminModelsAvatarDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/images/upload/prepare': {
      id: '/api/admin/images/upload/prepare'
      path: '/prepare'
      fullPath: '/api/admin/images/upload/prepare'
      preLoaderRoute: typeof ApiAdminImagesUploadPrepareRouteImport
      parentRoute: typeof ApiAdminImagesUploadRoute
    }
    '/api/admin/images/upload/complete': {
      id: '/api/admin/images/upload/complete'
      path: '/complete'
      fullPath: '/api/admin/images/upload/complete'
      preLoaderRoute: typeof ApiAdminImagesUploadCompleteRouteImport
      parentRoute: typeof ApiAdminImagesUploadRoute
    }
    '/api/admin/images/upload/cancel': {
      id: '/api/admin/images/upload/cancel'
      path: '/cancel'
      fullPath: '/api/admin/images/upload/cancel'
      preLoaderRoute: typeof ApiAdminImagesUploadCancelRouteImport
      parentRoute: typeof ApiAdminImagesUploadRoute
    }
    '/api/admin/models/avatar/upload/prepare': {
      id: '/api/admin/models/avatar/upload/prepare'
      path: '/prepare'
      fullPath: '/api/admin/models/avatar/upload/prepare'
      preLoaderRoute: typeof ApiAdminModelsAvatarUploadPrepareRouteImport
      parentRoute: typeof ApiAdminModelsAvatarUploadRoute
    }
    '/api/admin/models/avatar/upload/complete': {
      id: '/api/admin/models/avatar/upload/complete'
      path: '/complete'
      fullPath: '/api/admin/models/avatar/upload/complete'
      preLoaderRoute: typeof ApiAdminModelsAvatarUploadCompleteRouteImport
      parentRoute: typeof ApiAdminModelsAvatarUploadRoute
    }
  }
}

interface AdminAlbumsRouteRouteChildren {
  AdminAlbumsAlbumIdRoute: typeof AdminAlbumsAlbumIdRoute
  AdminAlbumsIndexRoute: typeof AdminAlbumsIndexRoute
}

const AdminAlbumsRouteRouteChildren: AdminAlbumsRouteRouteChildren = {
  AdminAlbumsAlbumIdRoute: AdminAlbumsAlbumIdRoute,
  AdminAlbumsIndexRoute: AdminAlbumsIndexRoute,
}

const AdminAlbumsRouteRouteWithChildren =
  AdminAlbumsRouteRoute._addFileChildren(AdminAlbumsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAlbumsRouteRoute: typeof AdminAlbumsRouteRouteWithChildren
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminTrashRoute: typeof AdminTrashRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAlbumsRouteRoute: AdminAlbumsRouteRouteWithChildren,
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminTrashRoute: AdminTrashRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiAdminImagesUploadRouteChildren {
  ApiAdminImagesUploadCancelRoute: typeof ApiAdminImagesUploadCancelRoute
  ApiAdminImagesUploadCompleteRoute: typeof ApiAdminImagesUploadCompleteRoute
  ApiAdminImagesUploadPrepareRoute: typeof ApiAdminImagesUploadPrepareRoute
}

const ApiAdminImagesUploadRouteChildren: ApiAdminImagesUploadRouteChildren = {
  ApiAdminImagesUploadCancelRoute: ApiAdminImagesUploadCancelRoute,
  ApiAdminImagesUploadCompleteRoute: ApiAdminImagesUploadCompleteRoute,
  ApiAdminImagesUploadPrepareRoute: ApiAdminImagesUploadPrepareRoute,
}

const ApiAdminImagesUploadRouteWithChildren =
  ApiAdminImagesUploadRoute._addFileChildren(ApiAdminImagesUploadRouteChildren)

interface ApiAdminModelsAvatarUploadRouteChildren {
  ApiAdminModelsAvatarUploadCompleteRoute: typeof ApiAdminModelsAvatarUploadCompleteRoute
  ApiAdminModelsAvatarUploadPrepareRoute: typeof ApiAdminModelsAvatarUploadPrepareRoute
}

const ApiAdminModelsAvatarUploadRouteChildren: ApiAdminModelsAvatarUploadRouteChildren =
  {
    ApiAdminModelsAvatarUploadCompleteRoute:
      ApiAdminModelsAvatarUploadCompleteRoute,
    ApiAdminModelsAvatarUploadPrepareRoute:
      ApiAdminModelsAvatarUploadPrepareRoute,
  }

const ApiAdminModelsAvatarUploadRouteWithChildren =
  ApiAdminModelsAvatarUploadRoute._addFileChildren(
    ApiAdminModelsAvatarUploadRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAssetsSplatRoute: ApiAssetsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  ApiAdminImagesUploadRoute: ApiAdminImagesUploadRouteWithChildren,
  ApiAdminModelsAvatarDeleteRoute: ApiAdminModelsAvatarDeleteRoute,
  ApiAdminModelsAvatarUploadRoute: ApiAdminModelsAvatarUploadRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
